<?php

declare(strict_types=1);

namespace WellDigit\Etruscan\Services;

use WellDigit\Etruscan\Mcp\Services\MapOverviewBuilder;
use WellDigit\Etruscan\Payloads\ParsedNote;
use WellDigit\Etruscan\Utilities\NodeSummaryLine;

/**
 * Renders the whole map as one compact markdown index, meant to be imported
 * into CLAUDE.md so it loads at session start.
 *
 * The vault's notes are served a few at a time through the map tools, which is
 * right for detail and wrong for orientation: a tool result arrives at the end
 * of the conversation, costs a round trip, and only exists if the agent thought
 * to ask. The index is small, changes only when the code does, and is the same
 * for every task — the shape a cached prefix is built for. So it is emitted
 * once and read for free thereafter.
 *
 * Deliberately deterministic: no timestamp, no counts that move on their own.
 * Re-exporting an unchanged map must produce a byte-identical file, or every
 * export dirties a diff and invalidates the prefix cache it exists to fill.
 */
#[\EtruscanNode('map-digest-renderer')]
#[\EtruscanLayer('service')]
#[\EtruscanContext('export')]
final readonly class MapDigestRenderer
{
    public function __construct(
        private MapOverviewBuilder $mapOverviewBuilder,
    ) {}

    /**
     * @param  array<string, ParsedNote>  $notesByAlias
     */
    public function __invoke(array $notesByAlias, string $axis, string $markerKey): string
    {
        $overview = ($this->mapOverviewBuilder)($notesByAlias, $axis, $markerKey);

        $lines = $this->header(count($notesByAlias), $overview['axis']);

        foreach ($overview['groups'] as $value => $aliases) {
            $lines[] = '';
            $lines[] = '## '.$value;
            $lines[] = '';

            foreach ($aliases as $alias) {
                $lines[] = NodeSummaryLine::render($notesByAlias[$alias]);
            }
        }

        return implode("\n", $lines)."\n";
    }

    /**
     * @return list<string>
     */
    private function header(int $nodes, string $axis): array
    {
        return [
            '# Codebase map',
            '',
            sprintf('%d nodes, grouped by [%s]. One line each: the alias, the file it lives in, and', $nodes, $axis),
            'what it is for.',
            '',
            'This is an index of the code, not a substitute for it — use it to decide which files',
            'to open, then open them. For a node\'s full description, its dependencies in both',
            'directions and any human notes, read its note in the vault or call the lookup-node map',
            'tool. On anything checkable — what is validated, authorized or guarded — the source is',
            'the authority.',
            '',
            'Generated by Etruscan; do not hand-edit. Refresh with `php artisan etruscan:export`',
            'after `php artisan etruscan:generate`.',
        ];
    }
}
